opam-version: "2.0"
name: "hello"
version: "0.1.0"
depends: [
  "dune"
  "zarith"
  "lambdasoup"
  "ppxlib"
  "mirage-crypto"
  "stdio"
  "ocamlfind"
  "ipaddr"
  "ocaml"
  "domain-name"
  "uarray"
  "stdlib-shims"
  "yojson"
  "uri"
  "bos"
  "faraday"
  "fmt"
  "ezjsonm"
  "core"
  "mtime"
  "alcotest"
  "base"
  "lwt"
  "containers"
  "ptime"
  "cohttp"
  "angstrom"
  "uutf"
  "ounit"
  "tyxml"
  "ppx_expect"
  "digestif"
  "hex"
  "re"
  "sexplib"
  "ppx_deriving"
  "cmdliner"
  "stringext"
  "async"
  "num"
  "findlib"
  "camlp-streams"
  "uunf"
  "logs"
  "easy-format"
  "fpath"
  "macaddr"
]
