package = "hello"
version = "0.1-1"
source = { url = "git+https://github.com/chaos/hello.git" }
dependencies = {
  "lpeg",
  "lua-resty-redis",
  "ansicolors",
  "luassert",
  "cluacov",
  "luasocket",
  "busted",
  "lrexlib-pcre",
  "middleclass",
  "lume",
  "lua-protobuf",
  "lua-cjson",
  "penlight",
  "date",
  "luaprofiler",
  "lua-term",
  "luacov",
  "luadbi",
  "luarocks-build-rust-mlua",
  "compat53",
  "luasec",
  "lua-curses",
  "luajson",
  "luaposix",
  "luasystem",
  "lua-zlib",
  "luacheck",
  "lua-resty-http",
  "mmd",
  "say",
  "inspect",
  "luasql-sqlite3",
  "cqueues",
  "luasignal",
  "coxpcall",
  "lua-ev",
  "dkjson",
  "luafilesystem",
  "coproas",
  "luv",
  "argparse",
}
