object Hello extends App {
  val deps = Seq(
    "org.postgresql:postgresql",
    "org.typelevel:cats-core",
    "com.typesafe.akka:akka-actor",
    "org.http4s:http4s-dsl",
    "com.github.scopt:scopt",
    "com.lihaoyi:os-lib",
    "org.scalameta:scalafmt-core",
    "com.zaxxer:HikariCP",
    "org.specs2:specs2-core",
    "dev.zio:zio",
    "org.typelevel:cats-effect",
    "com.typesafe.slick:slick",
    "org.scalacheck:scalacheck",
    "com.github.nscala-time:nscala-time",
    "com.github.pureconfig:pureconfig",
    "org.mongodb.scala:mongo-scala-driver",
    "org.scala-lang:scala-library",
    "com.typesafe.scala-logging:scala-logging",
    "com.lihaoyi:requests",
    "com.lihaoyi:upickle",
    "co.fs2:fs2-core",
    "ch.qos.logback:logback-classic",
    "io.getquill:quill-jdbc",
    "org.apache.spark:spark-sql",
    "org.scalamock:scalamock",
    "com.h2database:h2",
    "org.scalafx:scalafx",
    "org.apache.spark:spark-core",
    "com.typesafe.akka:akka-http",
    "com.typesafe.play:play-json",
    "org.typelevel:kittens",
    "org.tpolecat:doobie-core",
    "dev.zio:zio-streams",
    "com.typesafe:config",
    "com.typesafe.play:play",
    "com.typesafe.akka:akka-stream",
    "org.scalatest:scalatest",
    "org.rogach:scallop",
    "org.http4s:http4s-blaze-server",
    "com.softwaremill.sttp.client3:core",
    "io.circe:circe-generic",
    "io.circe:circe-core",
  )
  println(s"Loaded ${deps.size} of ${deps.size} sbt dependencies.")
  deps.foreach(d => println(s"  $d"))
  println("Hello World from chaos!")
}
