let deps = [
    "https://github.com/johnsundell/ShellOut",
    "https://github.com/apple/swift-log",
    "https://github.com/onevcat/Kingfisher",
    "https://github.com/apple/swift-collections",
    "https://github.com/basememara/Then",
    "https://github.com/krzysztofzablocki/Sourcery",
    "https://github.com/AliSoftware/OHHTTPStubs",
    "https://github.com/ReactiveX/RxSwift",
    "https://github.com/Alamofire/Alamofire",
    "https://github.com/nicklockwood/SwiftFormat",
    "https://github.com/Swinject/Swinject",
    "https://github.com/SnapKit/SnapKit",
    "https://github.com/apple/swift-atomics",
    "https://github.com/artman/Signals",
    "https://github.com/socketio/socket.io-client-swift",
    "https://github.com/apple/swift-nio",
    "https://github.com/pointfreeco/swift-dependencies",
    "https://github.com/nicklockwood/SwiftLint",
    "https://github.com/SwiftyJSON/SwiftyJSON",
    "https://github.com/evgenyneu/keychain-swift",
    "https://github.com/JohnSundell/Marathon",
    "https://github.com/ashleymills/Reachability.swift",
    "https://github.com/grpc/grpc-swift",
    "https://github.com/apple/swift-algorithms",
    "https://github.com/johnsundell/Files",
    "https://github.com/apple/swift-crypto",
    "https://github.com/weichsel/ZIPFoundation",
    "https://github.com/vapor/vapor",
    "https://github.com/AssistoLab/KotlinMultiplatform",
    "https://github.com/Hearst-DD/ObjectMapper",
    "https://github.com/Quick/Nimble",
    "https://github.com/ReactiveCocoa/ReactiveSwift",
    "https://github.com/kishikawakatsumi/KeychainAccess",
    "https://github.com/Moya/Moya",
    "https://github.com/SDWebImage/SDWebImage",
    "https://github.com/pointfreeco/swift-composable-architecture",
    "https://github.com/devxoul/Toaster",
    "https://github.com/firebase/firebase-ios-sdk",
    "https://github.com/apple/swift-metrics",
    "https://github.com/Quick/Quick",
]

print("Loaded \(deps.count) of \(deps.count) SwiftPM dependencies.")
for d in deps { print("  \(d)") }
print("Hello World from chaos!")
